name: check-audio

on:
    - push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Audio interfaces
              run: |
                apt install alsa
                aplay -l
