# References:
# - https://stackoverflow.com/questions/40061291/linux-without-hardware-soundcard-capture-audio-playback-and-record-it-to-fil

name: check-audio

on:
    - push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install audio utilities
              run: sudo apt -y install pulseaudio jackd2 alsa-utils dbus-x11

            - name: Audio interfaces
              run: |
                aplay -l
                python3 -m sounddevice
