# References:
# - https://stackoverflow.com/questions/40061291/linux-without-hardware-soundcard-capture-audio-playback-and-record-it-to-fil
# - https://alsa-project.org/wiki/Matrix:Module-dummy
# - https://newbedev.com/how-to-create-a-dummy-sound-card-device-in-linux-server

name: check-audio

on:
    - push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install audio utilities
              run: |
                sudo apt -y install pulseaudio jackd2 alsa-utils dbus-x11
                # Required for Python tests
                sudo apt -y install libportaudio2
                python -m pip install sounddevice

            - name: Audio interfaces
              run: |
                modinfo soundcore
                aplay -l
                python -c "import sounddevice as sd; print(sd.query_devices())"
