name: check-audio

on:
    - push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install ALSA
              run: sudo apt -y install alsa

            - name: Audio interfaces
              run: |
                aplay -l
